-- Migration: Add Phase 1 Dynamic Data Fetching fields to chart_generations table
-- This migration adds the necessary fields to support the hybrid approach for dynamic chart data fetching

-- Add new columns to chart_generations table
ALTER TABLE chart_generations ADD COLUMN IF NOT EXISTS generated_sql_query TEXT;
ALTER TABLE chart_generations ADD COLUMN IF NOT EXISTS sql_fields JSONB;
ALTER TABLE chart_generations ADD COLUMN IF NOT EXISTS spec_fields JSONB;
ALTER TABLE chart_generations ADD COLUMN IF NOT EXISTS fields_compatible BOOLEAN;
ALTER TABLE chart_generations ADD COLUMN IF NOT EXISTS dynamic_fetch_ready BOOLEAN DEFAULT false;

-- Add comments for the new fields
COMMENT ON COLUMN chart_generations.generated_sql_query IS 'The SQL query generated by AI for data aggregation';
COMMENT ON COLUMN chart_generations.sql_fields IS 'Fields returned by SQL query (for field mapping validation)';
COMMENT ON COLUMN chart_generations.spec_fields IS 'Fields expected by VChart spec (for field mapping validation)';
COMMENT ON COLUMN chart_generations.fields_compatible IS 'Whether SQL fields match spec fields exactly';
COMMENT ON COLUMN chart_generations.dynamic_fetch_ready IS 'Whether this chart is ready for dynamic data fetching';

-- Create index for querying charts ready for dynamic fetching
CREATE INDEX IF NOT EXISTS idx_chart_generations_dynamic_fetch_ready ON chart_generations(dynamic_fetch_ready) WHERE dynamic_fetch_ready = true;
CREATE INDEX IF NOT EXISTS idx_chart_generations_fields_compatible ON chart_generations(fields_compatible) WHERE fields_compatible IS NOT NULL;

-- Update existing records to be dynamic fetch ready if they have SQL queries
UPDATE chart_generations 
SET dynamic_fetch_ready = true 
WHERE sql_query IS NOT NULL AND sql_query != ''
  AND dynamic_fetch_ready IS NULL;

COMMIT;